# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: YarnInstaller@3
  displayName: 'Install yarn'
  inputs:
    versionSpec: '1.x'

- task: Yarn@3
  displayName: yarn install
  inputs:
    arguments: 'install'

- task: CmdLine@2
  displayName: yarn build
  inputs:
    script: 'NITRO_PRESET=azure yarn build'

- task: CopyFiles@2
  inputs:
    SourceFolder: '.output'
    Contents: '**'
    TargetFolder: '$(build.ArtifactStagingDirectory)'
    
- task: CopyFiles@2
  inputs:
    Contents: 'staticwebapp.config.json'
    TargetFolder: '$(build.ArtifactStagingDirectory)/public'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
